### ISSUE TITLE
PHP warning: Undefined global variable $TSFE

### ISSUE THREAD

**Issue by rschumachr** [lochmueller/focuspoint#103]
Hi there,

We recently set up a new project using TYPO3 v12.4 (with PHP 8.1). We've then installed focuscrop 6.0.2.
We now get the following PHP warnings. I believe the first error in the screenshot (Undefined array key "crop") only appears after setting the focus on an image, the other two appear on any page where we have images inserted.

So far I'm not certain if the warnings cause any actual problems. In the frontend the images don't get displayed at all, but it's a high possibility that that's a different issue. I'm just trying to figure out why we get these warnings about the global variable $TSFE.

![Screenshot 2023-08-03 at 13 28 08](https://github.com/lochmueller/focuspoint/assets/37555121/9bd9e946-696d-4ffe-8e3c-cbbf9b3ac054)

**Comment by FiveFuenf** [comment]
I'd like to add to that - TYPO3 v12.4.14, PHP 8.3. If I happen to reload an URL like `https://my.site/typo3/record/edit?edit%5Btt_content%5D%5B123%5D=edit`, the following Exception due to PHP Warnings is thrown:
![image](https://github.com/lochmueller/focuspoint/assets/79580234/5cd69b76-305f-461b-b70c-b4fa2a8399a0)

**Comment by lochmueller** [comment]
Both fixed in current master. Will be part of the next release.
