### ISSUE TITLE
static TypoScript is not showing up in template module in backend for integration

### ISSUE THREAD

**Issue by Karionis** [lochmueller/focuspoint#104]
TYPO3 11.5.30 Composer-Installation
focuspoint 5.1.0
PHP 8.2.8

It has to be included via TypoScript @import.

In focuspoint version 5.0.1 the static template was still available.

**Comment by lochmueller** [comment]
Hey @Karionis ,
sorry, but the old versions are not supported anymore.
In your case... EXT:autoloader find the file, but there is a missing TCA file in EXT:focuspoint.
If you want to patch this for your case?! Create `Configuration/TCA/Overrides/sys_file_reference.php` with this content should fix this issue:
```
<?php

$GLOBALS['TCA']['sys_template'] = \HDNET\Autoloader\Utility\ModelUtility::getTcaOverrideInformation('focuspoint', 'sys_template');
```

Otherwise, you could load the TypoSciript via regular include instead of the static selection in the backend.

Regards,
TIm
