### ISSUE TITLE
TYPO3 12.4 - If an image has no crop information, this leads to an error

### ISSUE THREAD

**Issue by monosize** [lochmueller/focuspoint#111]
[ERROR] Processing task of image file- Exception: PHP Warning: rename(/var/www/html/public/typo3temp/assets/images/bb244917dcb7b55f445298ac5cec10bc.jpg,/var/www/html/public/_processed_/6/f/csm_8a3ed22a9de3329b6d12c51e7554e6b5d99d1766-fp-1-1-0-0_fd7f8f556f.jpg): No such file or directory in /var/www/html/vendor/typo3/cms-core/Classes/Resource/Driver/LocalDriver.php line 803

Missing `fileadmin` in path!

Target must be /var/www/html/public/`fileadmin/_processed_/6/f/csm_8a3ed22a9de3329b6d12c51e7554e6b5d99d1766-fp-1-1-0-0_fd7f8f556f.jpg`

Problem located in Classes/Xclass/LocalCropScaleMaskHelper.php

https://github.com/lochmueller/focuspoint/blob/d63aacba82ff32db3b84522fb81e87518e74e46a/Classes/Xclass/LocalCropScaleMaskHelper.php#L84-L89

Maybe wrong storage for $targetFIle?

**Comment by lochmueller** [comment]
Hey @monosize ,
could you run same debugging in your instance? The "ObjectAccess::setProperty" is very dirty. Perhaps we replace to few properties for the new file?! Could you check "$file->getStorage()". This should be storge "1" with LocalFilesystem driver pointing to fileadmin. You can also check "$file->getPublicUrl()" and check if the URL is right?!
Regards,
Tim

**Comment by monosize** [comment]
$file Storage -> Driver -> absoluteBasePath is set to TYPO3_PATH_WEB
$targeFile Storage -> Dirver -> absoluteBasePath of is set to TYPO3_PATH_WEB + fileadmin

I think the storage of the $targetFile must not changed.

if there is no change to the storage of the $targetFile, then it works.

<img width="718" alt="image" src="https://github.com/lochmueller/focuspoint/assets/1583746/74fb8332-876e-4c62-bc72-88e7bc9552a0">

<img width="695" alt="image" src="https://github.com/lochmueller/focuspoint/assets/1583746/771b11c8-7c72-4614-9140-8dc087045692">

**Comment by lochmueller** [comment]
Hey @monosize ,

thanks for the explaintation. But I think this is not the source of the problem. Because if you combine the "absolteBasePath" of the storage with the "identifier" of the file, both are right. Because typo3temp is directly in the public dir and the _processed_ folder is in the fileadmin. And if we "change" the file, we also change the storgage, because the location is changed.

I try to reproduce the problem.... but I need some time and this could take some days/weeks.

Regards,
Tim

**Comment by monosize** [comment]
Sorry, the screenshot is from before the change.
Here is the data after the change in $targetFile

<img width="768" alt="image" src="https://github.com/lochmueller/focuspoint/assets/1583746/7b09df72-68c1-40f6-b47c-2bf3a440c7b8">

the combined path is then definitely not correct

`/var/www/html/public/`+ `/_processed_/4/7/csm_b5121f4839f6b911854de978f286335c51b9a793-fp-4-3-0-0_1fd4e6feac.jpg`

**Comment by lochmueller** [comment]
Hey @monosize ,

you are right. The line `ObjectAccess::setProperty($targetFile, 'storage', $file->getStorage(), true);` is strange I think. We do not reset the storage in the target file, because every file already has its storage and the storage could be different.

If you remove this line, everything works as expected?

Regards,
Tim

**Comment by monosize** [comment]
The problem only occurred when using the f:image ViewHelper.
When using the focuspoint:image ViewHelper there was no error, then $targetFile has the same storage as $file (typo3temp)

After removing the line it works with f:image

It also works with focuspoint:image Viewhelper
