### ISSUE TITLE
Remove autoloader dependency

### ISSUE THREAD

**Issue by cweiske** [lochmueller/focuspoint#25]
`focuspoint` depends on the [`autoloader` extension](https://typo3.org/extensions/repository/view/autoloader), which adds a whopping 7.3 MiB (51k LOC PHP) to our TYPO3 installation.

I'd rather not have all the zend classes here just because the used array merge method is also in that package.

**Comment by lochmueller** [comment]
There will be a composer only version in the near feature, that handle the dependencies much smarter. I will check this in the next weeks...

**Comment by tomhatzer** [comment]
Any news on this topic or an upgrade to the latest autoloader version? :)

**Comment by lochmueller** [comment]
Hey @tomhatzer 
Hey @cweiske 
I add EXT:autoloader 4.x support: https://github.com/lochmueller/focuspoint/commit/4b1025af9784d4f8d6adc55b17810a070ae36ed6
The new autoloader version is much smaller, because of the optional dependencies fpor the external frameworks.
So I will close this issue.
Note: I suggest to use composer mode!

Regards,
Tim
