### ISSUE TITLE
its not possible to install focuspoint on a TYPO3 9LTS

### ISSUE THREAD

**Issue by davidjakob** [lochmueller/focuspoint#67]
This Error occures every Time i try to install the Extension from TER:

![image](https://user-images.githubusercontent.com/4965254/53338291-993b5b80-3903-11e9-9951-dcc8f3710810.png)

**Comment by davidjakob** [comment]
Addition:
Installed Autoloader version: 6.0.6
TYPO3 Version: 9.5.4
PHP Version 7.2.13

**Comment by lochmueller** [comment]
Hey @davidjakob 

I try it in two of my installations and everything is fine. The problem was solved a few weeks ago:
https://github.com/lochmueller/focuspoint/commit/df167f02b9d81b2b01ae303ec1ea1d581847b5d6

Please check, why your installation load this file, because the loader is disabled and the class is loaded only in TYPO3 < 9.x

Best regards,
Tim

**Comment by davidjakob** [comment]
Yes, the Version from gitHub is installable!

Thanks!
